// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUkF6Tshwo98-5jkpHXmCgH7v9ajdlu8',
    appId: '1:933372458586:web:a5706b518bf0e782338a63',
    messagingSenderId: '933372458586',
    projectId: 'donorconnect-db692',
    authDomain: 'donorconnect-db692.firebaseapp.com',
    storageBucket: 'donorconnect-db692.appspot.com',
    measurementId: 'G-4ZWZNK95ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkksJqXhUEMUHWkyDPHjTedtJn9Q5D67M',
    appId: '1:933372458586:android:2864d2f14d24c6b8338a63',
    messagingSenderId: '933372458586',
    projectId: 'donorconnect-db692',
    storageBucket: 'donorconnect-db692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdVy6Z58r3knnb09lMQx1OJ-JKrk1j_iY',
    appId: '1:933372458586:ios:40c246230aa20ee6338a63',
    messagingSenderId: '933372458586',
    projectId: 'donorconnect-db692',
    storageBucket: 'donorconnect-db692.appspot.com',
    iosBundleId: 'com.example.donorconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdVy6Z58r3knnb09lMQx1OJ-JKrk1j_iY',
    appId: '1:933372458586:ios:40c246230aa20ee6338a63',
    messagingSenderId: '933372458586',
    projectId: 'donorconnect-db692',
    storageBucket: 'donorconnect-db692.appspot.com',
    iosBundleId: 'com.example.donorconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGUkF6Tshwo98-5jkpHXmCgH7v9ajdlu8',
    appId: '1:933372458586:web:c575c759ad5f7981338a63',
    messagingSenderId: '933372458586',
    projectId: 'donorconnect-db692',
    authDomain: 'donorconnect-db692.firebaseapp.com',
    storageBucket: 'donorconnect-db692.appspot.com',
    measurementId: 'G-XYXNJH0KPC',
  );
}
